name: Workflow of exercise 6
run-name: Sixth workflow

permissions: # Optional
  contents: read

# Events triggering the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Pandoc
        uses: docker://pandoc/extra

      - name: Convert exercise.md to PDF
        run: |
          pandoc --template eisvogel exercises.md -o exercises.pdf

      - name: Upload exercise PDF
        uses: actions/upload-artifact@v7
        with:
          name: exercises-pdf
          path: exercises.pdf

      - name: Convert slides.md to PDF (optional)
        id: convert_slides
        run: |
          if [ -f slides.md ]; then
            pandoc -t beamer slides.md -o slides.pdf
          else
            echo "Slides file not found."
            exit 0
          fi

      - name: Upload slides PDF (optional)
        uses: actions/upload-artifact@v7
        with:
          name: slides-pdf
          path: slides.pdf
        if: steps.convert_slides.outcome == 'success' # Upload only if slides.pdf was created
