name: Workflow of exercise 3
run-name: Third workflow

permissions: # Optional
  contents: read
  
# Events triggering the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  MyVariable: "Hello world"
  AnotherVariable: "Goodbye world"

jobs:
  print_variables:
    env:
      JobVariable: "This is a job variable"
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        run: |
          echo "${{ env.MyVariable }}"
          echo "${MyVariable}"
          echo "${{ env.AnotherVariable }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          echo "${{ github.token }}"

      - name: Set secret value to environment variable
        run: echo "MY_SECRET_VALUE=${{ secrets.MYSECRET }}" >> $GITHUB_ENV

      - name: Conditional step based on secret value
        if: ${{ env.MY_SECRET_VALUE == 'bob' }}
        run: echo "The secret has the chosen value!"
