name: Workflow of exercise 2
run-name: Second workflow

permissions: # Optional
  contents: read
  
# Events triggering the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Group of jobs to run as part of the workflow
jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, I'm ubuntu-latest"

  macos_job:
    runs-on: macos-latest
    steps:
      - run: echo "Hello, I'm macos-latest"

  slow_job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "Hello, I'm slow_job"
          sleep 30

  waiting_job:
    runs-on: ubuntu-latest
    needs: slow_job
    steps:
      - run: ls -l